db:
  name: postgres
  pool:
    size: 24
    timeout: 15
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
  properties:
    first: 1
    second: blabla
    third:
      size: 3
      timeout: 3

pool:
  size: 10

app:
  common:
    logging:
      enabled: true
      level: INFO

logging:
  level:
    root: INFO
    org.example.spring.bpp: INFO
    org.springframework.jdbc.core: TRACE
    org.example.logging: TRACE
spring:
  mvc:
    format:
      date: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  messages:
    basename: messages
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 722073332589-m9vv7jboc7uo2q5ka5rtsv59onohovuq.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

springdoc:
  swagger-ui:
    oauth:
      client-id: 722073332589-m9vv7jboc7uo2q5ka5rtsv59onohovuq.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
