db:
  name: postgres
  pool:
    size: 24
    timeout: 15
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
  properties:
    first: 1
    second: blabla
    third:
      size: 3
      timeout: 3

pool:
  size: 10

logging:
  level:
    root: INFO
    org.example.spring.bpp: INFO
    org.springframework.jdbc.core: TRACE
spring:
  mvc:
    format:
      date: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
