db:
  name: postgres
  pool:
    size: 24
    timeout: 15
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
  properties:
    first: 1
    second: blabla
    third:
      size: 3
      timeout: 3

pool:
  size: 10

logging:
  level:
    root: WARN
    org.example.spring.bpp: INFO